name: Android Build

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
    secrets:
      MAPBOX_ACCESS_TOKEN:
        required: true

jobs:
  lint_test_generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ inputs.node-version }}

      - name: set up JDK zulu 11
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: '11'

      - run: echo $MAPBOX_ACCESS_TOKEN > ./accesstoken
        working-directory: example
        env:
          MAPBOX_ACCESS_TOKEN: ${{ secrets.mapbox_access_token }}

      - run: yarn install --network-timeout 1000000
        working-directory: example

      - run: ./gradlew assemble
        working-directory: example/android
