name: On Push
on: [push]

env:
  NODE_VERSION: 14

jobs:
  lint_test_generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup node ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      - name: Lint Test Generate
        run: yarn install --network-timeout 1000000
        run: yarn run lint
        run: yarn run unittest
        run: yarn run generate
      
    outputs:
      NVMRC: ${{ steps.nvm.outputs.NVMRC }}

  call_android_workflow:
    needs: lint_test_generate
    uses: lisabaut/maps/.github/workflows/android-actions.yml@chore/pr-workflow
    with:
      node-version: ${{ needs.lint_test_generate.outputs.NVMRC }}
      MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}

  call_ios_workflow:
    needs: lint_test_generate
    uses: lisabaut/maps/.github/workflows/ios-actions.yml@chore/pr-workflow
    with:
      node-version: ${{ needs.lint_test_generate.outputs.NVMRC }}
      MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [lint_test_generate, call_android_workflow, call_ios_workflow]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ needs.lint_test_generate.outputs.NVMRC }}
          registry-url: https://registry.npmjs.org/
      - run: npm install --force && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
